### ISSUE TITLE
LTEではつながるが３Gでつながらない

### ISSUE THREAD

**Issue by emasachi** [ekazyam/LTE_3G_Card_Mounter#1]
LTEではつながるが３Gでつながらない状況です。サポートお願いします。

LTEでは確認出来るppp0が、3Gでは確認出来ません。
ppp0: flags=4305<UP,POINTOPOINT,RUNNING,NOARP,MULTICAST>  mtu 1500
        inet 10.241.98.110  netmask 255.255.255.255  destination 10.64.64.64
        ppp  txqueuelen 3  (Point-to-Pointプロトコル)
        RX packets 5  bytes 56 (56.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 6  bytes 89 (89.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by ekazyam** [comment]
通信種別はMini PCIEカードに依存します。
EC21-J Mini PCIeはLTEのみ、UC20-G Mini PCIeは3Gのみ通信可能の認識です。
正式なサポートではありませんが、他社のカードではLTE/3Gを併用可能な物も存在するようです。
目的に応じて使用を検討しては如何でしょうか？

**Comment by emasachi** [comment]
書き方が悪かったですが、EC21-J Mini PCIeTEではつながるがUC20-G Mini PCIeでつながらない状況です。

**Comment by ekazyam** [comment]
記載の以下の内容はUC20-G Mini PCIeのセットアップ後、ifconfigによるものですか？
>ppp0: flags=4305<UP,POINTOPOINT,RUNNING,NOARP,MULTICAST> mtu 1500
>inet 10.241.98.110 netmask 255.255.255.255 destination 10.64.64.64
>ppp txqueuelen 3 (Point-to-Pointプロトコル)
>RX packets 5 bytes 56 (56.0 B)
>RX errors 0 dropped 0 overruns 0 frame 0
>TX packets 6 bytes 89 (89.0 B)
>TX errors 0 dropped 0 overruns 0 carrier 0 collisions 0

**Comment by emasachi** [comment]
記載の内容はEC21-J Mini PCIeTEのセットアップ後、ifconfigによるものです。
その後、競合してそうなソフトのアンインストール等で状況改善したのですが、UC20-G Mini PCIe使用時に以下エラーが発生しています。

root@raspberrypi:~# wvdial
--> WvDial: Internet dialer version 1.61
--> Initializing modem.
--> Sending: ATZ
ATZ
OK
--> Sending: ATQ0 V1 E1 S0=0 &C1 &D2 +FCLASS=0
ATQ0 V1 E1 S0=0 &C1 &D2 +FCLASS=0
OK
--> Sending: AT+CGDCONT=1,"IP","soracom.io"
AT+CGDCONT=1,"IP","soracom.io"
OK
--> Modem initialized.
--> Sending: ATD*99***1#
--> Waiting for carrier.
ATD*99***1#
ERROR
--> Invalid dial command.
--> Disconnecting at Mon May  7 10:59:37 2018

**Comment by ekazyam** [comment]
wvdialの結果から、以下の様な状況と確認しました。
1.デバイスの認識→成功
2.wvdialの実行→失敗

2.の実行内容を確認すると、wvdialが内部で実行しているATZコマンドがデバイスに対して応答を得られています。これらの情報から1.の条件は通り、デバイスはOSから正しく認識しています。
> ATZ
OK

2.のwvdialの最後に実行している3Gへ接続を行うコマンドで失敗が確認されます。
これらのエラーが頻発した場合、以下の項目を試してみて下さい。

a.アンテナの接続不良
a-1. UC20-G Mini PCIeの「MAIN」端子へアンテナが接続されているか確認

b.電波不調
b-1.UC20-G Mini PCIeの「MAIN」と「DIV(GPSではない端子)」に新規にアンテナを増設
b-2.デバイスの設置箇所を変更

**Comment by emasachi** [comment]
以下確認しました。
a-1. UC20-G Mini PCIeの「MAIN」端子へアンテナが接続されているか確認  
OK
b-1.UC20-G Mini PCIeの「MAIN」と「DIV(GPSではない端子)」に新規にアンテナを増設
変化なし
b-2.デバイスの設置箇所を変更
candypi 3Gでは接続できている。

というか、そもそも　”OS起動時に自動でLTE/3Gネットワークへ接続する”　設定をしているのですが、つながっていません。

**Comment by ekazyam** [comment]
確認をありがとうございます。
基板検証時に想定していない接続不良ということで認識しました。
こちらで3Gモジュールを使用した検証を進めるので、原因が特定でき次第追記します。

**Comment by ekazyam** [comment]
動作確認を行いました。
/etc/wvdial.confの以下の箇所を変更することで外部と疎通できることを確認しましたので、お試しください。
正：Modem = /dev/ttyUSB3
誤：Modem = /dev/ttyUSB2

[ターミナルログ]
<デバイス接続確認>
root@raspberrypi:/etc# lsusb
Bus 001 Device 004: ID 05c6:9003 Qualcomm, Inc. Quectel UC20
Bus 001 Device 003: ID 0424:ec00 Standard Microsystems Corp. SMSC9512/9514 Fast Ethernet Adapter
Bus 001 Device 002: ID 0424:9514 Standard Microsystems Corp. SMC9514 Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

<インタフェースのIP割当確認(IP伏せ)>
root@raspberrypi:/etc# ifconfig ppp0
ppp0: flags=4305<UP,POINTOPOINT,RUNNING,NOARP,MULTICAST>  mtu 1500
        inet x.x.x.x  netmask 255.255.255.255  destination 10.64.64.64
        ppp  txqueuelen 3  (Point-to-Point Protocol)
        RX packets 16  bytes 905 (905.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 18  bytes 1109 (1.0 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

<Pingによる疎通確認>
root@raspberrypi:/etc# ping -I ppp0 8.8.8.8
PING 8.8.8.8 (8.8.8.8) from x.x.x.x ppp0: 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=57 time=2288 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=57 time=189 ms

**Comment by emasachi** [comment]
つながりました。　有り難うございます。

**Comment by ekazyam** [comment]
ご確認ありがとうございます。
頂いた情報は品質向上の為、マニュアルに反映します。
ご協力ありがとうございました。
